sudo: required
group: trusty_latest
services: docker
language: python

# Only build master. PRs still get built.
branches:
  only:
    - master

env:
  global:
    - IMAGE_USER=praekeltfoundation
    - REGISTRY_USER=praekeltorgdeploy
    - secure: "gJZqz0DVsgnxZwkZmUsIAuMMZzIItrj6xaIhHgnYHCtS2Qls2S0FrwhgUtHCNnBhFet2vEurTA4sB76mD8Xr0daEFdqhjB/vpPLAThM+T969mSprfECkz2RJFX3N79TaM8wuOHKT8Xqvf14BhyOlIUou3T27E5/X1q2EUAJk3eb6jruNHogedyXzYuwWM6uWoMFov7UzDdB6FWa4y2266/I/exXjDgcYq/a073xtRANnWVVLks5Jz+TFCPl5zyEFFQNzk7Q2a9S8CNpLXwnA8MfsRksnq+B5/9EwndEsajGl29Pe6GgVGIX/KqmEky3VI0FEorM9DhgBn/Bc+5E6Quv+1k4ZfpCfNX9w/uU70NfN2EHqXjwjpd8LOfZ3w/J7f+tr5MwZksE4wQRqZiA6mv953Mt20B5GVgPRkXzyd9QiiaA9Ry2zSxLxJBSPlAzM6cEeKUlJ9ykhATS1H/YAGlnfT3HXgVJRYAqQ+xL7XMB4ZUE3qEdFWBFZKF9xX3vflr6klubAPB/VcWHCF8HLBiQfeEKuZEw+uLK+I4wLVwWk3tzqcoGInjixi5DcN8Uq4A8XrOBMPjDfu7j6PpaoHQOf4/pX8DmX79DVsrY1+fZLiXa94lscSjT55V7Ec809PDyXIn8O/0QRFSJw8e5iwQ8BuMg1S4Lkvj8NewzgTOI="
  matrix:
    - BASE_OS=alpine FROM_IMAGE=python:2.7.15-alpine3.7    TAGS="alpine3.7 alpine" VERSION_LATEST=1
    - BASE_OS=alpine FROM_IMAGE=python:3.6.5-alpine3.7     TAGS="alpine3.7 alpine" VERSION_LATEST=
    - BASE_OS=debian FROM_IMAGE=pypy:2-6.0.0-slim          TAGS="jessie latest"    VERSION_LATEST=1
    - BASE_OS=debian FROM_IMAGE=pypy:3-6.0.0-slim          TAGS="jessie latest"    VERSION_LATEST=
    - BASE_OS=debian FROM_IMAGE=python:2.7.15-slim-jessie  TAGS="jessie latest"    VERSION_LATEST=1
    - BASE_OS=debian FROM_IMAGE=python:2.7.15-slim-stretch TAGS="stretch"          VERSION_LATEST=1
    - BASE_OS=debian FROM_IMAGE=python:3.6.5-slim-jessie   TAGS="jessie latest"    VERSION_LATEST=
    - BASE_OS=debian FROM_IMAGE=python:3.6.5-slim-stretch  TAGS="stretch"          VERSION_LATEST=

before_script:
  # Find the Python: 'python' or 'pypy'
  - python="${FROM_IMAGE%:*}"
  # Find the full version: '2-5.8.0', '2.7.13'...
  - version="$(echo "$FROM_IMAGE" | grep -oP '(\d+-)?\d+(\.\d+)*' | head -1)"
  # Find the major Python version: '2-5.8.0' => '2', '2.7.13' => '2.7'
  - maj_version="$(echo "${version%-*}" | grep -oP '^\d+(\.\d+)?')"
  - tags=($TAGS); tag="$maj_version-${tags[0]}"
  - image_tag="$IMAGE_USER/${python}-base:$tag"
  - echo "Building image '$image_tag' based on '$FROM_IMAGE' with version '$version'..."
  # Pull existing image to use as cache
  - docker pull "$image_tag" || true
script:
  - travis_retry docker build --pull --cache-from "$image_tag" --tag "$image_tag" --build-arg FROM_IMAGE="$FROM_IMAGE" "$BASE_OS"
after_script:
  - docker images

# Deploy to Docker Hub (default registry) using docker-ci-deploy
before_deploy:
  - pip install docker-ci-deploy==0.3.0
  - echo "$REGISTRY_PASS" | docker login --username "$REGISTRY_USER" --password-stdin
deploy:
  provider: script
  script: dcd --tag $TAGS --version $version --version-semver ${VERSION_LATEST:+--version-latest} "$image_tag"
  on:
    branch: master

notifications:
  slack:
    rooms:
      # praekeltfoundation:<token>#docker
      - secure: "Bd6P16v4xi4UCiqWYAJTBGRlIj/da0KqAeXYUM6VuZnxefPrqOdYM3dlJbdbqIsGKILG2eNFJvyujaAaUZAe4XZudRcXb/IWADBFszllWDc5rNAw12/kLd8iWFVZq03pwokZPZh8kxqjCTpSQQP1DQhBFZXIUApJKSuuwtdWoxXXG3hb6v7Uh4y5HT9rMeHUPx7F/86i7QiXs3o4280dzYANjpN88i7PRnk6eQLEwxWHaXEaCXeDLD6nOdSaZrD4C9Im/gD+EckPFrMeXQCW8FNhk4ZGDMiDjG9YzwX+PoVN0KfHvXjUe78Iy2Yul8vLV6GVURZC8Ul65+DlHFRPhUu/1cjeQCMeI5/eRYSFwy9VDqLWvs4sokk0mApWHwJILr/trrkmEOKXW1OysWAPwcbCi/g27wiVJtj9Wz9f+afM9rVS6U2/FqGLCZsKnwDsF942fMFQ6SqTXSiK58gJg7Bv1z4yOpog3aL9I3qAUaUw0xOqrSh96ZgVoeUfh2lBZ6HhKOBGIZaiQ6pfwHxmKeFpVawngvdP+/3tx/2W1fHrFLk7o9VJqU9RMR9XWvyo5Jq5ZXZsmfH3JWR9Vo9fWp3amw4udVGGe7NhqckqrPGe/uAzJKR2qV3+g1PQ7lgcfgAQ/qbJxYoH8soEeob+ojiuOEu0+2MisRWvuQkXvIc="
    on_pull_requests: false
