name: Build docker image
on:
  push:
    branches:
      - master
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: "2.7.18"
            dist: stretch
            python: python
          - version: "3.6.14"
            dist: stretch
            python: python
          - version: "3.7.11"
            dist: stretch
            python: python
          - version: "3.8.11"
            dist: buster
            python: python
          - version: "3.9.6"
            dist: buster
            python: python
          - version: "2.7"
            version_suffix: "-7.3.5"
            dist: buster
            python: pypy
          - version: "3.6"
            version_suffix: "-7.3.3"
            dist: buster
            python: pypy

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: construct image metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            praekeltfoundation/${{matrix.python}}-base
            ghcr.io/praekeltfoundation/${{matrix.python}}-base
          tags: |
            type=pep440,pattern={{version}},value=${{matrix.version}}
            type=pep440,pattern={{major}}.{{minor}},value=${{matrix.version}}
            type=pep440,pattern={{major}},value=${{matrix.version}}
            type=raw,value=${{matrix.dist}}
            type=pep440,pattern={{version}}-${{matrix.dist}},value=${{matrix.version}}
            type=pep440,pattern={{major}}.{{minor}}-${{matrix.dist}},value=${{matrix.version}}
            type=pep440,pattern={{major}}-${{matrix.dist}},value=${{matrix.version}}
      - name: login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{github.event_name != 'pull_request'}}
          tags: ${{steps.meta.outputs.tags}}
          build-args: |
            FROM_IMAGE=${{matrix.python}}:${{matrix.version}}${{matrix.version_suffix}}-slim-${{matrix.dist}}

  build-no-wheelhouse:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dist: [buster, bullseye]
        version: ["3.10.2", "3.9.10", "3.8.12"]
        python: [python]
        include:
          - version: "2.7"
            version_suffix: "-7.3.5"
            dist: buster
            python: pypy
          - version: "3.6"
            version_suffix: "-7.3.3"
            dist: buster
            python: pypy

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: construct image metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/praekeltfoundation/${{matrix.python}}-base-nw
          tags: |
            type=pep440,pattern={{version}},value=${{matrix.version}}
            type=pep440,pattern={{major}}.{{minor}},value=${{matrix.version}}
            type=pep440,pattern={{major}},value=${{matrix.version}}
            type=raw,value=${{matrix.dist}}
            type=pep440,pattern={{version}}-${{matrix.dist}},value=${{matrix.version}}
            type=pep440,pattern={{major}}.{{minor}}-${{matrix.dist}},value=${{matrix.version}}
            type=pep440,pattern={{major}}-${{matrix.dist}},value=${{matrix.version}}
      - name: login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.no-wheelhouse
          load: true
          push: ${{github.event_name != 'pull_request'}}
          tags: ${{steps.meta.outputs.tags}}
          build-args: |
            FROM_IMAGE=${{matrix.python}}:${{matrix.version}}${{matrix.version_suffix}}-slim-${{matrix.dist}}
      - name: Snyk Container Test
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ Secrets.SNYK_TOKEN }}
        with:
          image: ${{steps.meta.outputs.tags[0]}}
          args: --file=Dockerfile.no-wheelhouse
      - name: Upload Container Scan results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
